# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gp_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10gp_manager.proto\x12\ngp_manager\"S\n\x0bgpCreateReq\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07service\x18\x04 \x01(\t\" \n\x0bgpCreateRep\x12\x11\n\tisCreated\x18\x01 \x01(\x08\x32N\n\tGpCreator\x12\x41\n\x0bgroupCreate\x12\x17.gp_manager.gpCreateReq\x1a\x17.gp_manager.gpCreateRep\"\x00\x42(\n\x0e/SDCC/servicesB\x0eGpManagerProtoP\x01\xa2\x02\x03GPMb\x06proto3')



_GPCREATEREQ = DESCRIPTOR.message_types_by_name['gpCreateReq']
_GPCREATEREP = DESCRIPTOR.message_types_by_name['gpCreateRep']
gpCreateReq = _reflection.GeneratedProtocolMessageType('gpCreateReq', (_message.Message,), {
  'DESCRIPTOR' : _GPCREATEREQ,
  '__module__' : 'gp_manager_pb2'
  # @@protoc_insertion_point(class_scope:gp_manager.gpCreateReq)
  })
_sym_db.RegisterMessage(gpCreateReq)

gpCreateRep = _reflection.GeneratedProtocolMessageType('gpCreateRep', (_message.Message,), {
  'DESCRIPTOR' : _GPCREATEREP,
  '__module__' : 'gp_manager_pb2'
  # @@protoc_insertion_point(class_scope:gp_manager.gpCreateRep)
  })
_sym_db.RegisterMessage(gpCreateRep)

_GPCREATOR = DESCRIPTOR.services_by_name['GpCreator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\016GpManagerProtoP\001\242\002\003GPM'
  _GPCREATEREQ._serialized_start=32
  _GPCREATEREQ._serialized_end=115
  _GPCREATEREP._serialized_start=117
  _GPCREATEREP._serialized_end=149
  _GPCREATOR._serialized_start=151
  _GPCREATOR._serialized_end=229
# @@protoc_insertion_point(module_scope)
