# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.gp_manager_pb2 as gp__manager__pb2


class GpCreatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.groupCreate = channel.unary_unary(
                '/gp_manager.GpCreator/groupCreate',
                request_serializer=gp__manager__pb2.gpCreateReq.SerializeToString,
                response_deserializer=gp__manager__pb2.gpCreateRep.FromString,
                )


class GpCreatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def groupCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GpCreatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'groupCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.groupCreate,
                    request_deserializer=gp__manager__pb2.gpCreateReq.FromString,
                    response_serializer=gp__manager__pb2.gpCreateRep.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gp_manager.GpCreator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GpCreator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def groupCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gp_manager.GpCreator/groupCreate',
            gp__manager__pb2.gpCreateReq.SerializeToString,
            gp__manager__pb2.gpCreateRep.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
