# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sharedpw.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esharedpw.proto\x12\tshared_pw\"=\n\tShRequest\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65xtra\x18\x03 \x01(\t\"\x1a\n\x07ShReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"K\n\x07respMsg\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\"\x1a\n\x07respRep\x12\x0f\n\x07message\x18\x01 \x01(\t\"[\n\x07InfoMsg\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x03(\t\x12\r\n\x05token\x18\x03 \x03(\t\x12\x0f\n\x07\x63reator\x18\x04 \x01(\t\x12\r\n\x05\x65xtra\x18\x05 \x01(\t\"\x1b\n\x08InfoResp\x12\x0f\n\x07message\x18\x01 \x01(\t2\xac\x01\n\x06Shared\x12\x35\n\x07makeReq\x12\x14.shared_pw.ShRequest\x1a\x12.shared_pw.ShReply\"\x00\x12\x34\n\x08sendResp\x12\x12.shared_pw.respMsg\x1a\x12.shared_pw.respRep\"\x00\x12\x35\n\x08sendInfo\x12\x12.shared_pw.InfoMsg\x1a\x13.shared_pw.InfoResp\"\x00\x42\'\n\x0e/SDCC/servicesB\rSharedPwProtoP\x01\xa2\x02\x03SHPb\x06proto3')



_SHREQUEST = DESCRIPTOR.message_types_by_name['ShRequest']
_SHREPLY = DESCRIPTOR.message_types_by_name['ShReply']
_RESPMSG = DESCRIPTOR.message_types_by_name['respMsg']
_RESPREP = DESCRIPTOR.message_types_by_name['respRep']
_INFOMSG = DESCRIPTOR.message_types_by_name['InfoMsg']
_INFORESP = DESCRIPTOR.message_types_by_name['InfoResp']
ShRequest = _reflection.GeneratedProtocolMessageType('ShRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHREQUEST,
  '__module__' : 'sharedpw_pb2'
  # @@protoc_insertion_point(class_scope:shared_pw.ShRequest)
  })
_sym_db.RegisterMessage(ShRequest)

ShReply = _reflection.GeneratedProtocolMessageType('ShReply', (_message.Message,), {
  'DESCRIPTOR' : _SHREPLY,
  '__module__' : 'sharedpw_pb2'
  # @@protoc_insertion_point(class_scope:shared_pw.ShReply)
  })
_sym_db.RegisterMessage(ShReply)

respMsg = _reflection.GeneratedProtocolMessageType('respMsg', (_message.Message,), {
  'DESCRIPTOR' : _RESPMSG,
  '__module__' : 'sharedpw_pb2'
  # @@protoc_insertion_point(class_scope:shared_pw.respMsg)
  })
_sym_db.RegisterMessage(respMsg)

respRep = _reflection.GeneratedProtocolMessageType('respRep', (_message.Message,), {
  'DESCRIPTOR' : _RESPREP,
  '__module__' : 'sharedpw_pb2'
  # @@protoc_insertion_point(class_scope:shared_pw.respRep)
  })
_sym_db.RegisterMessage(respRep)

InfoMsg = _reflection.GeneratedProtocolMessageType('InfoMsg', (_message.Message,), {
  'DESCRIPTOR' : _INFOMSG,
  '__module__' : 'sharedpw_pb2'
  # @@protoc_insertion_point(class_scope:shared_pw.InfoMsg)
  })
_sym_db.RegisterMessage(InfoMsg)

InfoResp = _reflection.GeneratedProtocolMessageType('InfoResp', (_message.Message,), {
  'DESCRIPTOR' : _INFORESP,
  '__module__' : 'sharedpw_pb2'
  # @@protoc_insertion_point(class_scope:shared_pw.InfoResp)
  })
_sym_db.RegisterMessage(InfoResp)

_SHARED = DESCRIPTOR.services_by_name['Shared']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\rSharedPwProtoP\001\242\002\003SHP'
  _SHREQUEST._serialized_start=29
  _SHREQUEST._serialized_end=90
  _SHREPLY._serialized_start=92
  _SHREPLY._serialized_end=118
  _RESPMSG._serialized_start=120
  _RESPMSG._serialized_end=195
  _RESPREP._serialized_start=197
  _RESPREP._serialized_end=223
  _INFOMSG._serialized_start=225
  _INFOMSG._serialized_end=316
  _INFORESP._serialized_start=318
  _INFORESP._serialized_end=345
  _SHARED._serialized_start=348
  _SHARED._serialized_end=520
# @@protoc_insertion_point(module_scope)
