apiVersion: apps/v1
kind: Deployment
metadata:
  name: newpw-deployment
  labels: 
    app: newpw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newpw
  template:
    metadata:
      labels:
        app: newpw
    spec:
      containers:
      - name: newpw
        image: newpw-image
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 150m
          requests:
            cpu: 100m
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: newpw-service
spec:
  selector:
    app: newpw
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: newpw-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: newpw-deployment
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50