# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x05login\">\n\nLogRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x08\"\x1c\n\x08LogReply\x12\x10\n\x08isLogged\x18\x01 \x01(\x08\" \n\x0c\x45mailRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1b\n\nEmailReply\x12\r\n\x05\x65mail\x18\x01 \x01(\t2n\n\x05Login\x12/\n\x07\x64oLogin\x12\x11.login.LogRequest\x1a\x0f.login.LogReply\"\x00\x12\x34\n\x08getEmail\x12\x13.login.EmailRequest\x1a\x11.login.EmailReply\"\x00\x42$\n\x0e/SDCC/servicesB\nLoginProtoP\x01\xa2\x02\x03LOGb\x06proto3')



_LOGREQUEST = DESCRIPTOR.message_types_by_name['LogRequest']
_LOGREPLY = DESCRIPTOR.message_types_by_name['LogReply']
_EMAILREQUEST = DESCRIPTOR.message_types_by_name['EmailRequest']
_EMAILREPLY = DESCRIPTOR.message_types_by_name['EmailReply']
LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.LogRequest)
  })
_sym_db.RegisterMessage(LogRequest)

LogReply = _reflection.GeneratedProtocolMessageType('LogReply', (_message.Message,), {
  'DESCRIPTOR' : _LOGREPLY,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.LogReply)
  })
_sym_db.RegisterMessage(LogReply)

EmailRequest = _reflection.GeneratedProtocolMessageType('EmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMAILREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.EmailRequest)
  })
_sym_db.RegisterMessage(EmailRequest)

EmailReply = _reflection.GeneratedProtocolMessageType('EmailReply', (_message.Message,), {
  'DESCRIPTOR' : _EMAILREPLY,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.EmailReply)
  })
_sym_db.RegisterMessage(EmailReply)

_LOGIN = DESCRIPTOR.services_by_name['Login']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\nLoginProtoP\001\242\002\003LOG'
  _LOGREQUEST._serialized_start=22
  _LOGREQUEST._serialized_end=84
  _LOGREPLY._serialized_start=86
  _LOGREPLY._serialized_end=114
  _EMAILREQUEST._serialized_start=116
  _EMAILREQUEST._serialized_end=148
  _EMAILREPLY._serialized_start=150
  _EMAILREPLY._serialized_end=177
  _LOGIN._serialized_start=179
  _LOGIN._serialized_end=289
# @@protoc_insertion_point(module_scope)
