# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"H\n\x12\x43heckStatusRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\"1\n\x10\x43heckStatusReply\x12\x0e\n\x06status\x18\x01 \x01(\x11\x12\r\n\x05total\x18\x02 \x01(\x05\"\x91\x01\n\x1aNotificationMessageRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x17\n\x0f\x65mail_applicant\x18\x03 \x01(\t\x12\x14\n\x0c\x65mail_member\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x06 \x01(\x08\"(\n\x18NotificationMessageReply\x12\x0c\n\x04isOk\x18\x01 \x01(\x08\x32\xc6\x01\n\x0cNotification\x12Q\n\x0b\x63heckStatus\x12 .notification.CheckStatusRequest\x1a\x1e.notification.CheckStatusReply\"\x00\x12\x63\n\racceptDecline\x12(.notification.NotificationMessageRequest\x1a&.notification.NotificationMessageReply\"\x00\x42+\n\x0e/SDCC/servicesB\x11NotificationProtoP\x01\xa2\x02\x03NTPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\021NotificationProtoP\001\242\002\003NTP'
  _CHECKSTATUSREQUEST._serialized_start=36
  _CHECKSTATUSREQUEST._serialized_end=108
  _CHECKSTATUSREPLY._serialized_start=110
  _CHECKSTATUSREPLY._serialized_end=159
  _NOTIFICATIONMESSAGEREQUEST._serialized_start=162
  _NOTIFICATIONMESSAGEREQUEST._serialized_end=307
  _NOTIFICATIONMESSAGEREPLY._serialized_start=309
  _NOTIFICATIONMESSAGEREPLY._serialized_end=349
  _NOTIFICATION._serialized_start=352
  _NOTIFICATION._serialized_end=550
# @@protoc_insertion_point(module_scope)
