# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.notification_pb2 as notification__pb2


class NotificationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.checkStatus = channel.unary_unary(
                '/notification.Notification/checkStatus',
                request_serializer=notification__pb2.CheckStatusRequest.SerializeToString,
                response_deserializer=notification__pb2.CheckStatusReply.FromString,
                )
        self.acceptDecline = channel.unary_unary(
                '/notification.Notification/acceptDecline',
                request_serializer=notification__pb2.NotificationMessageRequest.SerializeToString,
                response_deserializer=notification__pb2.NotificationMessageReply.FromString,
                )


class NotificationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def checkStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def acceptDecline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'checkStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.checkStatus,
                    request_deserializer=notification__pb2.CheckStatusRequest.FromString,
                    response_serializer=notification__pb2.CheckStatusReply.SerializeToString,
            ),
            'acceptDecline': grpc.unary_unary_rpc_method_handler(
                    servicer.acceptDecline,
                    request_deserializer=notification__pb2.NotificationMessageRequest.FromString,
                    response_serializer=notification__pb2.NotificationMessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notification.Notification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notification(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def checkStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.Notification/checkStatus',
            notification__pb2.CheckStatusRequest.SerializeToString,
            notification__pb2.CheckStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def acceptDecline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/notification.Notification/acceptDecline',
            notification__pb2.NotificationMessageRequest.SerializeToString,
            notification__pb2.NotificationMessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
