# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sharedpw_pb2 as sharedpw__pb2


class SharedStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makeReq = channel.unary_unary(
                '/shared_pw.Shared/makeReq',
                request_serializer=sharedpw__pb2.ShRequest.SerializeToString,
                response_deserializer=sharedpw__pb2.ShReply.FromString,
                )
        self.sendResp = channel.unary_unary(
                '/shared_pw.Shared/sendResp',
                request_serializer=sharedpw__pb2.respMsg.SerializeToString,
                response_deserializer=sharedpw__pb2.respRep.FromString,
                )
        self.sendInfo = channel.unary_unary(
                '/shared_pw.Shared/sendInfo',
                request_serializer=sharedpw__pb2.InfoMsg.SerializeToString,
                response_deserializer=sharedpw__pb2.InfoResp.FromString,
                )


class SharedServicer(object):
    """Missing associated documentation comment in .proto file."""

    def makeReq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendResp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SharedServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeReq': grpc.unary_unary_rpc_method_handler(
                    servicer.makeReq,
                    request_deserializer=sharedpw__pb2.ShRequest.FromString,
                    response_serializer=sharedpw__pb2.ShReply.SerializeToString,
            ),
            'sendResp': grpc.unary_unary_rpc_method_handler(
                    servicer.sendResp,
                    request_deserializer=sharedpw__pb2.respMsg.FromString,
                    response_serializer=sharedpw__pb2.respRep.SerializeToString,
            ),
            'sendInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.sendInfo,
                    request_deserializer=sharedpw__pb2.InfoMsg.FromString,
                    response_serializer=sharedpw__pb2.InfoResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shared_pw.Shared', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Shared(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def makeReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shared_pw.Shared/makeReq',
            sharedpw__pb2.ShRequest.SerializeToString,
            sharedpw__pb2.ShReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendResp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shared_pw.Shared/sendResp',
            sharedpw__pb2.respMsg.SerializeToString,
            sharedpw__pb2.respRep.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/shared_pw.Shared/sendInfo',
            sharedpw__pb2.InfoMsg.SerializeToString,
            sharedpw__pb2.InfoResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
