# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: newpassword.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11newpassword.proto\x12\x05newpw\"h\n\x12NewPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0e\n\x06length\x18\x03 \x01(\x05\x12\x0f\n\x07symbols\x18\x04 \x01(\x08\x12\x11\n\thasToSave\x18\x05 \x01(\x08\"5\n\x10NewPasswordReply\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x0f\n\x07isSaved\x18\x02 \x01(\x08\x32\xc7\x02\n\x08Password\x12M\n\x15GetNewNumericPassword\x12\x19.newpw.NewPasswordRequest\x1a\x17.newpw.NewPasswordReply\"\x00\x12K\n\x13GetNewLowerPassword\x12\x19.newpw.NewPasswordRequest\x1a\x17.newpw.NewPasswordReply\"\x00\x12K\n\x13GetNewUpperPassword\x12\x19.newpw.NewPasswordRequest\x1a\x17.newpw.NewPasswordReply\"\x00\x12R\n\x1aGetNewAlphaNumericPassword\x12\x19.newpw.NewPasswordRequest\x1a\x17.newpw.NewPasswordReply\"\x00\x42$\n\x0e/SDCC/servicesB\nNewPwProtoP\x01\xa2\x02\x03NPWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'newpassword_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\nNewPwProtoP\001\242\002\003NPW'
  _NEWPASSWORDREQUEST._serialized_start=28
  _NEWPASSWORDREQUEST._serialized_end=132
  _NEWPASSWORDREPLY._serialized_start=134
  _NEWPASSWORDREPLY._serialized_end=187
  _PASSWORD._serialized_start=190
  _PASSWORD._serialized_end=517
# @@protoc_insertion_point(module_scope)
