# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: savepwd.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsavepwd.proto\x12\x06savepw\"<\n\x0bSaveRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02pw\x18\x02 \x01(\x05\x12\x0f\n\x07service\x18\x03 \x01(\t\"\x1d\n\tSaveReply\x12\x10\n\x08isStored\x18\x01 \x01(\x08\x32;\n\x05Saver\x12\x32\n\x06SavePw\x12\x13.savepw.SaveRequest\x1a\x11.savepw.SaveReply\"\x00\x42%\n\x0e/SDCC/servicesB\x0bSavePwProtoP\x01\xa2\x02\x03SPWb\x06proto3')



_SAVEREQUEST = DESCRIPTOR.message_types_by_name['SaveRequest']
_SAVEREPLY = DESCRIPTOR.message_types_by_name['SaveReply']
SaveRequest = _reflection.GeneratedProtocolMessageType('SaveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SAVEREQUEST,
  '__module__' : 'savepwd_pb2'
  # @@protoc_insertion_point(class_scope:savepw.SaveRequest)
  })
_sym_db.RegisterMessage(SaveRequest)

SaveReply = _reflection.GeneratedProtocolMessageType('SaveReply', (_message.Message,), {
  'DESCRIPTOR' : _SAVEREPLY,
  '__module__' : 'savepwd_pb2'
  # @@protoc_insertion_point(class_scope:savepw.SaveReply)
  })
_sym_db.RegisterMessage(SaveReply)

_SAVER = DESCRIPTOR.services_by_name['Saver']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\013SavePwProtoP\001\242\002\003SPW'
  _SAVEREQUEST._serialized_start=25
  _SAVEREQUEST._serialized_end=85
  _SAVEREPLY._serialized_start=87
  _SAVEREPLY._serialized_end=116
  _SAVER._serialized_start=118
  _SAVER._serialized_end=177
# @@protoc_insertion_point(module_scope)
