# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x05login\"=\n\tPwRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x08\"\x1b\n\x07PwReply\x12\x10\n\x08isLogged\x18\x01 \x01(\x08\x32\x36\n\x05Login\x12-\n\x07\x64oLogin\x12\x10.login.PwRequest\x1a\x0e.login.PwReply\"\x00\x42$\n\x0e/SDCC/servicesB\nLoginProtoP\x01\xa2\x02\x03LOGb\x06proto3')



_PWREQUEST = DESCRIPTOR.message_types_by_name['PwRequest']
_PWREPLY = DESCRIPTOR.message_types_by_name['PwReply']
PwRequest = _reflection.GeneratedProtocolMessageType('PwRequest', (_message.Message,), {
  'DESCRIPTOR' : _PWREQUEST,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.PwRequest)
  })
_sym_db.RegisterMessage(PwRequest)

PwReply = _reflection.GeneratedProtocolMessageType('PwReply', (_message.Message,), {
  'DESCRIPTOR' : _PWREPLY,
  '__module__' : 'login_pb2'
  # @@protoc_insertion_point(class_scope:login.PwReply)
  })
_sym_db.RegisterMessage(PwReply)

_LOGIN = DESCRIPTOR.services_by_name['Login']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\nLoginProtoP\001\242\002\003LOG'
  _PWREQUEST._serialized_start=22
  _PWREQUEST._serialized_end=83
  _PWREPLY._serialized_start=85
  _PWREPLY._serialized_end=112
  _LOGIN._serialized_start=114
  _LOGIN._serialized_end=168
# @@protoc_insertion_point(module_scope)
