# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blogin.proto\x12\x05login\"K\n\x13RegistrationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08isAgency\x18\x03 \x01(\x08\")\n\x11RegistrationReply\x12\x14\n\x0cisRegistered\x18\x01 \x01(\x08\"D\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x10\n\x08isAgency\x18\x03 \x01(\x08\"\x1e\n\nLoginReply\x12\x10\n\x08isLogged\x18\x01 \x01(\x11\"5\n\x14\x43heckEmployeeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06\x61gency\x18\x02 \x01(\t\"/\n\x12\x43heckEmployeeReply\x12\x19\n\x11isEmployeeChecked\x18\x01 \x01(\x11\"3\n\x12\x41\x64\x64\x45mployeeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06\x61gency\x18\x02 \x01(\t\"+\n\x10\x41\x64\x64\x45mployeeReply\x12\x17\n\x0fisEmployeeAdded\x18\x01 \x01(\x08\"$\n\x12\x43heckAgencyRequest\x12\x0e\n\x06\x61gency\x18\x01 \x01(\t\"+\n\x10\x43heckAgencyReply\x12\x17\n\x0fisAgencyChecked\x18\x01 \x01(\x08\x32\xd9\x02\n\x05Login\x12\x46\n\x0cregistration\x12\x1a.login.RegistrationRequest\x1a\x18.login.RegistrationReply\"\x00\x12\x33\n\x07\x64oLogin\x12\x13.login.LoginRequest\x1a\x11.login.LoginReply\"\x00\x12I\n\rcheckEmployee\x12\x1b.login.CheckEmployeeRequest\x1a\x19.login.CheckEmployeeReply\"\x00\x12\x43\n\x0b\x61\x64\x64\x45mployee\x12\x19.login.AddEmployeeRequest\x1a\x17.login.AddEmployeeReply\"\x00\x12\x43\n\x0b\x63heckAgency\x12\x19.login.CheckAgencyRequest\x1a\x17.login.CheckAgencyReply\"\x00\x42$\n\x0e/SDCC/servicesB\nLoginProtoP\x01\xa2\x02\x03LOGb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'login_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\nLoginProtoP\001\242\002\003LOG'
  _REGISTRATIONREQUEST._serialized_start=22
  _REGISTRATIONREQUEST._serialized_end=97
  _REGISTRATIONREPLY._serialized_start=99
  _REGISTRATIONREPLY._serialized_end=140
  _LOGINREQUEST._serialized_start=142
  _LOGINREQUEST._serialized_end=210
  _LOGINREPLY._serialized_start=212
  _LOGINREPLY._serialized_end=242
  _CHECKEMPLOYEEREQUEST._serialized_start=244
  _CHECKEMPLOYEEREQUEST._serialized_end=297
  _CHECKEMPLOYEEREPLY._serialized_start=299
  _CHECKEMPLOYEEREPLY._serialized_end=346
  _ADDEMPLOYEEREQUEST._serialized_start=348
  _ADDEMPLOYEEREQUEST._serialized_end=399
  _ADDEMPLOYEEREPLY._serialized_start=401
  _ADDEMPLOYEEREPLY._serialized_end=444
  _CHECKAGENCYREQUEST._serialized_start=446
  _CHECKAGENCYREQUEST._serialized_end=482
  _CHECKAGENCYREPLY._serialized_start=484
  _CHECKAGENCYREPLY._serialized_end=527
  _LOGIN._serialized_start=530
  _LOGIN._serialized_end=875
# @@protoc_insertion_point(module_scope)
