# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: doubleauth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64oubleauth.proto\x12\x05newpw\"0\n\x0eGenCodeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"@\n\x10\x43heckCodeRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\"5\n\x13RegistrationRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32\xc2\x01\n\nDoubleauth\x12\x39\n\x10\x64oLoginThirdPart\x12\x15.newpw.GenCodeRequest\x1a\x0c.newpw.Reply\"\x00\x12\x34\n\tcheckCode\x12\x17.newpw.CheckCodeRequest\x1a\x0c.newpw.Reply\"\x00\x12\x43\n\x15registrationThirdPart\x12\x1a.newpw.RegistrationRequest\x1a\x0c.newpw.Reply\"\x00\x42#\n\x0e/SDCC/servicesB\nDoubleAuthP\x01\xa2\x02\x02\x44\x41\x62\x06proto3')



_GENCODEREQUEST = DESCRIPTOR.message_types_by_name['GenCodeRequest']
_CHECKCODEREQUEST = DESCRIPTOR.message_types_by_name['CheckCodeRequest']
_REGISTRATIONREQUEST = DESCRIPTOR.message_types_by_name['RegistrationRequest']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
GenCodeRequest = _reflection.GeneratedProtocolMessageType('GenCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENCODEREQUEST,
  '__module__' : 'doubleauth_pb2'
  # @@protoc_insertion_point(class_scope:newpw.GenCodeRequest)
  })
_sym_db.RegisterMessage(GenCodeRequest)

CheckCodeRequest = _reflection.GeneratedProtocolMessageType('CheckCodeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKCODEREQUEST,
  '__module__' : 'doubleauth_pb2'
  # @@protoc_insertion_point(class_scope:newpw.CheckCodeRequest)
  })
_sym_db.RegisterMessage(CheckCodeRequest)

RegistrationRequest = _reflection.GeneratedProtocolMessageType('RegistrationRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTRATIONREQUEST,
  '__module__' : 'doubleauth_pb2'
  # @@protoc_insertion_point(class_scope:newpw.RegistrationRequest)
  })
_sym_db.RegisterMessage(RegistrationRequest)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'doubleauth_pb2'
  # @@protoc_insertion_point(class_scope:newpw.Reply)
  })
_sym_db.RegisterMessage(Reply)

_DOUBLEAUTH = DESCRIPTOR.services_by_name['Doubleauth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\nDoubleAuthP\001\242\002\002DA'
  _GENCODEREQUEST._serialized_start=27
  _GENCODEREQUEST._serialized_end=75
  _CHECKCODEREQUEST._serialized_start=77
  _CHECKCODEREQUEST._serialized_end=141
  _REGISTRATIONREQUEST._serialized_start=143
  _REGISTRATIONREQUEST._serialized_end=196
  _REPLY._serialized_start=198
  _REPLY._serialized_end=222
  _DOUBLEAUTH._serialized_start=225
  _DOUBLEAUTH._serialized_end=419
# @@protoc_insertion_point(module_scope)
