# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sharedpw.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esharedpw.proto\x12\x08sharedpw\"K\n\x15SharedPasswordRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\"7\n\x13SharedPasswordReply\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x10\n\x08password\x18\x02 \x01(\t\"a\n\x1a\x43heckSharedPasswordRequest\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61gency\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"-\n\x18\x43heckSharedPasswordReply\x12\x11\n\tisChecked\x18\x01 \x01(\x08\x32\xba\x01\n\x06Shared\x12S\n\x0fpasswordRequest\x12\x1f.sharedpw.SharedPasswordRequest\x1a\x1d.sharedpw.SharedPasswordReply\"\x00\x12[\n\rcheckPassword\x12$.sharedpw.CheckSharedPasswordRequest\x1a\".sharedpw.CheckSharedPasswordReply\"\x00\x42\'\n\x0e/SDCC/servicesB\rSharedPwProtoP\x01\xa2\x02\x03SHPb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sharedpw_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\rSharedPwProtoP\001\242\002\003SHP'
  _SHAREDPASSWORDREQUEST._serialized_start=28
  _SHAREDPASSWORDREQUEST._serialized_end=103
  _SHAREDPASSWORDREPLY._serialized_start=105
  _SHAREDPASSWORDREPLY._serialized_end=160
  _CHECKSHAREDPASSWORDREQUEST._serialized_start=162
  _CHECKSHAREDPASSWORDREQUEST._serialized_end=259
  _CHECKSHAREDPASSWORDREPLY._serialized_start=261
  _CHECKSHAREDPASSWORDREPLY._serialized_end=306
  _SHARED._serialized_start=309
  _SHARED._serialized_end=495
# @@protoc_insertion_point(module_scope)
