# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: managepassword.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14managepassword.proto\x12\x08managepw\"G\n\x13SavePasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\"%\n\x11SavePasswordReply\x12\x10\n\x08isStored\x18\x01 \x01(\x08\"$\n\x13ListPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"u\n\x11ListPasswordReply\x12\x33\n\x04list\x18\x01 \x03(\x0b\x32%.managepw.ListPasswordReply.ListEntry\x1a+\n\tListEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x9d\x01\n\x05Saver\x12L\n\x0cSavePassword\x12\x1d.managepw.SavePasswordRequest\x1a\x1b.managepw.SavePasswordReply\"\x00\x12\x46\n\x06\x64oList\x12\x1d.managepw.ListPasswordRequest\x1a\x1b.managepw.ListPasswordReply\"\x00\x42%\n\x0e/SDCC/servicesB\x0bSavePwProtoP\x01\xa2\x02\x03SPWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'managepassword_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\013SavePwProtoP\001\242\002\003SPW'
  _LISTPASSWORDREPLY_LISTENTRY._options = None
  _LISTPASSWORDREPLY_LISTENTRY._serialized_options = b'8\001'
  _SAVEPASSWORDREQUEST._serialized_start=34
  _SAVEPASSWORDREQUEST._serialized_end=105
  _SAVEPASSWORDREPLY._serialized_start=107
  _SAVEPASSWORDREPLY._serialized_end=144
  _LISTPASSWORDREQUEST._serialized_start=146
  _LISTPASSWORDREQUEST._serialized_end=182
  _LISTPASSWORDREPLY._serialized_start=184
  _LISTPASSWORDREPLY._serialized_end=301
  _LISTPASSWORDREPLY_LISTENTRY._serialized_start=258
  _LISTPASSWORDREPLY_LISTENTRY._serialized_end=301
  _SAVER._serialized_start=304
  _SAVER._serialized_end=461
# @@protoc_insertion_point(module_scope)
