apiVersion: apps/v1
kind: Deployment
metadata:
  name: groupmanager-deployment
  labels: 
    app: groupmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groupmanager
  template:
    metadata:
      labels:
        app: groupmanager
    spec:
      containers:
      - name: groupmanager
        image: groupmanager-image
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 150m
          requests:
            cpu: 100m
        ports:
        - containerPort: 50057
---
apiVersion: v1
kind: Service
metadata:
  name: groupmanager-service
spec:
  selector:
    app: groupmanager
  ports:
    - protocol: TCP
      port: 50057
      targetPort: 50057
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: groupmanager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: groupmanager-deployment
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50