apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-deployment
  labels: 
    app: listing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listing
  template:
    metadata:
      labels:
        app: listing
    spec:
      containers:
      - name: listing
        image: listing_image
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: listing-service
spec:
  selector:
    app: listing
  ports:
    - protocol: TCP
      port: 3001 # porta su cui è in ascolto il Service
      targetPort: 3001 # porta su cui è in ascolto il container
                       # deve matchare con la containerPort