apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels: 
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp-image
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000       # porta su cui è in ascolto il Service
      targetPort: 5000 # porta su cui è in ascolto il container
                       # deve matchare con la containerPort
      nodePort: 30000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
	- type: Object
		object:
		  metric:
			name: requests-per-second
		  describedObject:
			apiVersion: networking.k8s.io/v1
			kind: Ingress
			name: main-route
		  target:
			type: Value
			value: 10k    