apiVersion: apps/v1
kind: Deployment
metadata:
  name: managepw-deployment
  labels: 
    app: managepw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: managepw
  template:
    metadata:
      labels:
        app: managepw
    spec:
      containers:
      - name: managepw
        image: managepw-image
        imagePullPolicy: Never 
        resources:
          limits:
            cpu: 150m
          requests:
            cpu: 100m
        ports:
        - containerPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: managepw-service
spec:
  selector:
    app: managepw
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: managepw-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: managepw-deployment
  minReplicas: 1
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0
    scaleUp:
      stabilizationWindowSeconds: 0
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50
