# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: register.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregister.proto\x12\x08register\">\n\tPwRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"\x1f\n\x07PwReply\x12\x14\n\x0cisRegistered\x18\x01 \x01(\x08\x32\x44\n\x08Register\x12\x38\n\x0cregistration\x12\x13.register.PwRequest\x1a\x11.register.PwReply\"\x00\x42\'\n\x0e/SDCC/servicesB\rRegisterProtoP\x01\xa2\x02\x03REGb\x06proto3')



_PWREQUEST = DESCRIPTOR.message_types_by_name['PwRequest']
_PWREPLY = DESCRIPTOR.message_types_by_name['PwReply']
PwRequest = _reflection.GeneratedProtocolMessageType('PwRequest', (_message.Message,), {
  'DESCRIPTOR' : _PWREQUEST,
  '__module__' : 'register_pb2'
  # @@protoc_insertion_point(class_scope:register.PwRequest)
  })
_sym_db.RegisterMessage(PwRequest)

PwReply = _reflection.GeneratedProtocolMessageType('PwReply', (_message.Message,), {
  'DESCRIPTOR' : _PWREPLY,
  '__module__' : 'register_pb2'
  # @@protoc_insertion_point(class_scope:register.PwReply)
  })
_sym_db.RegisterMessage(PwReply)

_REGISTER = DESCRIPTOR.services_by_name['Register']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016/SDCC/servicesB\rRegisterProtoP\001\242\002\003REG'
  _PWREQUEST._serialized_start=28
  _PWREQUEST._serialized_end=90
  _PWREPLY._serialized_start=92
  _PWREPLY._serialized_end=123
  _REGISTER._serialized_start=125
  _REGISTER._serialized_end=193
# @@protoc_insertion_point(module_scope)
