apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-deployment
  labels: 
    app: register
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: register-image
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
        ports:
        - containerPort: 50053
---
apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  selector:
    app: register
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053